[workspace]
members = ["crates/format"]

[package]
name = "pactfmt"
version = "0.1.0"
edition = "2021"

[dependencies]
format = { path = "crates/format" }
clap = { version = "4.5.20", features = ["derive"] }

[dev-dependencies]
insta = "1.41.1"
