[package]
name = "pactfmt-docs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
formatter = { path = "../../../crates/formatter" }
syntax = { path = "../../../crates/syntax" }
strip-ansi-escapes = "0.2.1"
