[package]
name = "formatter"
version = "0.1.0"
edition = "2021"

[dependencies]
syntax = { path = "../syntax" }
pretty = "0.12.3"

[dev-dependencies]
insta = "1.41.1"
pretty_assertions = "1.4.0"
test_each_file = "0.3.4"
test-utils = { path = "../test-utils" }
