name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - run: |
          cargo clippy --locked -- -D warnings
          cargo fmt --check

  test:
    name: Test
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Pact
        run: |
          PACT_VERSION=5.1
          wget -nv https://github.com/kadena-io/pact/releases/download/v$PACT_VERSION/pact-$PACT_VERSION-linux-x64.tar.gz
          tar -xzf pact-$PACT_VERSION-linux-x64.tar.gz
          chmod +x pact
          mv pact .bin/

      - name: Add Pact to PATH
        run: echo "PATH=$PATH:$GITHUB_WORKSPACE/.bin" >> $GITHUB_ENV

      - run: cargo test --workspace --verbose
